name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - source

jobs:
  github-pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      ## jekyll-actions has been deprecated, in case of failure this needs to be
      ## removed. see https://github.com/helaili/jekyll-action#-deprecation-notice-
      - uses: helaili/jekyll-action@2.5.0 
        with:
          token: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
